#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# lib/blue-zone-manifest.sh — the two artefacts generated from a staged tree:
#
#   blue_zone_write_manifest  BLUE_ZONE_MANIFEST.md — the Claude-readable
#                             inventory of files that were STRIPPED
#   blue_zone_write_overlay   docker-compose.blue-zone.yml — the generated
#                             per-folder mount overlay
#
# Both are regenerated by prepare-blue-zone.sh AND by sync-in.sh: a mid-session
# refresh can change which files exist on the host, so a manifest written at
# prepare time would go stale and misinform Claude about the project's shape.
#
# Sourced, not executed. Requires blue-zone.config.sh to be sourced first, and
# expects STAGED_ROOT_FILES to be set by blue_zone_project_into.
# ─────────────────────────────────────────────────────────────────────────────

: "${BOLD:=}" "${GREEN:=}" "${YELLOW:=}" "${RED:=}" "${RESET:=}"

# ─────────────────────────────────────────────────────────────────────────────
# Blue zone manifest — a Claude-readable record of what was STRIPPED. For each
# configured folder it lists the source files that did NOT make it into the blue
# zone (removed by a filename exclusion rule or the content denylist): the files
# that exist on the host but are deliberately absent from the workspace. Mounted
# read-only into the container at /workspace/<name> so Claude knows the true
# shape of the project — which files exist as red zone — without ever seeing
# their contents. Written at the blue zone root (not inside a mounted folder) so
# sync-back never carries it back into the repo.
#
# Must be called from the repo root: "./$folder" is the real source and
# "$BLUE_ZONE_ROOT/$folder" is the filtered staging copy.
# ─────────────────────────────────────────────────────────────────────────────
blue_zone_write_manifest() {
  echo -e "${BOLD}[manifest]${RESET} recording stripped (red-zone) files"
  local MANIFEST_OUT="$BLUE_ZONE_ROOT/$BLUE_ZONE_MANIFEST_FILE"
  local STRIPPED_TMP MANIFEST_DENY_FILE MANIFEST_TMP
  local STRIPPED_TOTAL=0
  local folder rf p f PER SRC_LIST STAGED_LIST BLUE_N RED_N SHOWN_LIST HIDDEN_N DN REDACTED
  STRIPPED_TMP="$(mktemp -d)"

  # Active content-denylist strings (the "insecure words"). The manifest is
  # mounted where Claude can read it, so it must not contain any of them: a
  # stripped file whose NAME carries one is omitted from the listing below, and
  # — as a final safety net — the whole assembled manifest is filtered before it
  # is written out (a red-zone rule pattern can itself equal a denylist entry,
  # e.g. `google-services.json`). The manifest is assembled into MANIFEST_TMP
  # first and the filtered result is written to MANIFEST_OUT.
  MANIFEST_DENY_FILE="$(mktemp)"
  blue_zone_denylist_strings > "$MANIFEST_DENY_FILE"
  MANIFEST_TMP="$STRIPPED_TMP/manifest.md"

  # Header + summary table. Detail sections are appended in a second pass so the
  # per-folder stripped lists are computed only once (cached under STRIPPED_TMP).
  {
    echo "# Blue Zone Manifest"
    echo
    echo "_Auto-generated by \`prepare-blue-zone.sh\` on $(date -u '+%Y-%m-%d %H:%M:%SZ'). Read-only — do not edit._"
    echo
    echo "Everything in \`/workspace\` was filtered from the host repository before it"
    echo "was mounted. This manifest records what was **stripped** — files that exist"
    echo "on the host but are deliberately **not** in your workspace (red zone)."
    echo
    echo "Use it to understand the true shape of the project: know that these files"
    echo "exist so you code against their contracts and do not recreate them, but"
    echo "never ask for their contents — they are withheld on purpose."
    echo
    echo "## Summary"
    echo
    echo "| Folder | Mounted (blue) | Stripped (red) |"
    echo "| ------ | -------------: | -------------: |"
  } > "$MANIFEST_TMP"

  for folder in "${BLUE_ZONE_FOLDERS[@]}"; do
    if [ ! -d "./$folder" ]; then
      : > "$STRIPPED_TMP/$folder"
      echo "| \`$folder\` | _absent_ | _absent_ |" >> "$MANIFEST_TMP"
      continue
    fi
    # Source files (minus heavy/irrelevant trees) vs what actually got staged.
    # The difference is everything the filename excludes AND the content
    # denylist kept out.
    SRC_LIST="$( (cd "./$folder" && find . -type f \
        -not -path './node_modules/*' -not -path './.git/*' 2>/dev/null) \
        | sed 's|^\./||' | sort )"
    STAGED_LIST="$( (cd "$BLUE_ZONE_ROOT/$folder" && find . -type f 2>/dev/null) \
        | sed 's|^\./||' | sort )"
    comm -23 <(printf '%s\n' "$SRC_LIST") <(printf '%s\n' "$STAGED_LIST") \
        | grep -v '^$' > "$STRIPPED_TMP/$folder" || true

    BLUE_N=$(printf '%s\n' "$STAGED_LIST" | grep -c . || true)
    RED_N=$(grep -c . "$STRIPPED_TMP/$folder" || true)
    STRIPPED_TOTAL=$((STRIPPED_TOTAL + RED_N))
    echo "| \`$folder\` | $BLUE_N | $RED_N |" >> "$MANIFEST_TMP"
  done

  {
    echo
    echo "## Stripped files (red zone)"
    echo
    echo "Present on the host but removed before mounting. Not in your workspace and"
    echo "cannot be read."
    for folder in "${BLUE_ZONE_FOLDERS[@]}"; do
      echo
      echo "### $folder"
      echo
      if [ ! -s "$STRIPPED_TMP/$folder" ]; then
        echo "_Nothing stripped from this folder._"
      else
        # Omit any stripped path whose name contains a denylisted (insecure)
        # word, so the manifest never surfaces one. Matching mirrors the content
        # denylist: case-insensitive, fixed-string (substring).
        SHOWN_LIST="$STRIPPED_TMP/$folder"
        HIDDEN_N=0
        if [ -s "$MANIFEST_DENY_FILE" ]; then
          grep -viFf "$MANIFEST_DENY_FILE" "$STRIPPED_TMP/$folder" \
            > "$STRIPPED_TMP/$folder.shown" || true
          HIDDEN_N=$(( $(grep -c . "$STRIPPED_TMP/$folder" || true) \
                     - $(grep -c . "$STRIPPED_TMP/$folder.shown" || true) ))
          SHOWN_LIST="$STRIPPED_TMP/$folder.shown"
        fi
        while IFS= read -r f; do
          [ -n "$f" ] || continue
          echo "- \`$folder/$f\`"
        done < "$SHOWN_LIST"
        if [ "$HIDDEN_N" -gt 0 ]; then
          echo "- _$HIDDEN_N file(s) omitted — name contains a denylisted string._"
        fi
      fi
    done
    echo
    echo "## Root files"
    echo
    if [ "${#BLUE_ZONE_ROOT_FILES[@]}" -eq 0 ]; then
      echo "_None configured._"
    else
      for rf in "${BLUE_ZONE_ROOT_FILES[@]}"; do
        if [ -f "$BLUE_ZONE_ROOT/$rf" ]; then
          echo "- \`$rf\` — mounted at \`/workspace/$rf\`"
        else
          echo "- \`$rf\` — **not available** (absent, refused, or dropped by the content denylist)"
        fi
      done
    fi
    echo
    echo "## Why these were stripped"
    echo
    echo "Files are removed by the red-zone filename rules below or because their"
    echo "contents matched a forbidden string. Source of truth: \`blue-zone.config.sh\`."
    echo
    echo "### Filename rules — every folder"
    echo
    for p in "${BLUE_ZONE_COMMON_EXCLUDES[@]}"; do
      echo "- \`$p\`"
    done
    for folder in "${BLUE_ZONE_FOLDERS[@]}"; do
      PER="$(blue_zone_excludes_for "$folder")"
      [ -n "$PER" ] || continue
      echo
      echo "### Filename rules — $folder"
      echo
      printf '%s\n' "$PER" | while IFS= read -r p; do
        [ -n "$p" ] || continue
        echo "- \`$p\`"
      done
    done
    echo
    echo "### Content denylist"
    echo
    if [ -n "$(blue_zone_denylist_strings)" ]; then
      DN=$(blue_zone_denylist_strings | grep -c . || true)
      echo "Active — any staged file whose contents matched one of $DN forbidden"
      echo "string(s) was dropped as well."
    else
      echo "Inactive — no content strings are configured."
    fi
  } >> "$MANIFEST_TMP"

  # Final safety net: write the manifest out with any line carrying a denylisted
  # string dropped, so the mounted manifest can never contain one (matching
  # mirrors the denylist: case-insensitive, fixed-string). `>` truncates
  # MANIFEST_OUT in place, preserving its inode so a live single-file mount
  # survives a re-run.
  if [ -s "$MANIFEST_DENY_FILE" ]; then
    grep -viFf "$MANIFEST_DENY_FILE" "$MANIFEST_TMP" > "$MANIFEST_OUT" || true
    REDACTED=$(( $(wc -l < "$MANIFEST_TMP") - $(wc -l < "$MANIFEST_OUT") ))
    if [ "$REDACTED" -gt 0 ]; then
      { echo
        echo "_$REDACTED line(s) redacted from this manifest for containing a denylisted string; see \`blue-zone.config.sh\` for the full red-zone rules._"
      } >> "$MANIFEST_OUT"
    fi
  else
    cat "$MANIFEST_TMP" > "$MANIFEST_OUT"
  fi

  rm -rf "$STRIPPED_TMP"
  rm -f "$MANIFEST_DENY_FILE"
  echo -e "  ${GREEN}✓ manifest written${RESET} ($STRIPPED_TOTAL file(s) stripped) → mounted read-only at /workspace/$BLUE_ZONE_MANIFEST_FILE\n"
}

# ─────────────────────────────────────────────────────────────────────────────
# Generate the docker-compose overlay that mounts each configured folder into
# both Claude services. Layered on top of docker-compose.ai-sandbox.yml via COMPOSE_FILE by
# start-cli.sh / run-headless.sh. Regenerated every run — never edit by hand.
#
# Usage: blue_zone_write_overlay <project-root>
# ─────────────────────────────────────────────────────────────────────────────
blue_zone_write_overlay() {
  local PROJECT_ROOT="$1"
  local COMPOSE_OUT="$PROJECT_ROOT/$BLUE_ZONE_COMPOSE_FILE"
  local svc folder rf
  {
    echo "# ─────────────────────────────────────────────────────────────────────"
    echo "# AUTO-GENERATED by prepare-blue-zone.sh from blue-zone.config.sh."
    echo "# Regenerated on every prepare run — do NOT edit by hand."
    echo "# Mounts each configured blue-zone folder into both Claude services,"
    echo "# plus the read-only blue zone manifest at /workspace/$BLUE_ZONE_MANIFEST_FILE."
    echo "# ─────────────────────────────────────────────────────────────────────"
    echo "services:"
    for svc in claude-code claude-cli; do
      echo "  $svc:"
      echo "    volumes:"
      for folder in "${BLUE_ZONE_FOLDERS[@]}"; do
        echo "      - $BLUE_ZONE_ROOT/$folder:/workspace/$folder"
      done
      # Configured root files (writable, like folders — synced back on exit).
      for rf in ${STAGED_ROOT_FILES[@]+"${STAGED_ROOT_FILES[@]}"}; do
        [ -f "$BLUE_ZONE_ROOT/$rf" ] && echo "      - $BLUE_ZONE_ROOT/$rf:/workspace/$rf"
      done
      # Read-only manifest of what was stripped, so Claude knows the true
      # project shape. Lives at the blue zone root, mounted into /workspace.
      echo "      - $BLUE_ZONE_ROOT/$BLUE_ZONE_MANIFEST_FILE:/workspace/$BLUE_ZONE_MANIFEST_FILE:ro"
    done
  } > "$COMPOSE_OUT"
}
